/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.java.lab2_thuchanh;

import javax.swing.JOptionPane;

/**
 *
 * @author phuon
 */
public class cau_3 extends javax.swing.JFrame {

    /**
     * Creates new form cau_3
     */
    public cau_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnOpen = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnSaveAs = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnEmail = new javax.swing.JButton();
        btnCall = new javax.swing.JButton();
        btnPresent = new javax.swing.JButton();
        btnAlarm = new javax.swing.JButton();
        btnZoom = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnClick = new javax.swing.JButton();
        btnChart = new javax.swing.JButton();
        btnLock = new javax.swing.JButton();
        btnPencil = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setForeground(new java.awt.Color(204, 204, 255));
        jToolBar1.setRollover(true);

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/java/lab2_thuchanh/icon_cau3/Open folder.png"))); // NOI18N
        btnOpen.setFocusable(false);
        btnOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOpen);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/java/lab2_thuchanh/icon_cau3/Save.png"))); // NOI18N
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);

        btnSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/java/lab2_thuchanh/icon_cau3/Save as.png"))); // NOI18N
        btnSaveAs.setFocusable(false);
        btnSaveAs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveAs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSaveAs);

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/java/lab2_thuchanh/icon_cau3/Print preview.png"))); // NOI18N
        btnPrint.setFocusable(false);
        btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPrint);

        btnEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/java/lab2_thuchanh/icon_cau3/Mail.png"))); // NOI18N
        btnEmail.setFocusable(false);
        btnEmail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmail.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmailActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEmail);

        btnCall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/java/lab2_thuchanh/icon_cau3/Call.png"))); // NOI18N
        btnCall.setFocusable(false);
        btnCall.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCall.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCallActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCall);

        btnPresent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/java/lab2_thuchanh/icon_cau3/List.png"))); // NOI18N
        btnPresent.setFocusable(false);
        btnPresent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPresent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPresent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresentActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPresent);

        btnAlarm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/java/lab2_thuchanh/icon_cau3/Alarm.png"))); // NOI18N
        btnAlarm.setFocusable(false);
        btnAlarm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlarm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAlarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlarmActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAlarm);

        btnZoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/java/lab2_thuchanh/icon_cau3/Search.png"))); // NOI18N
        btnZoom.setFocusable(false);
        btnZoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnZoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoomActionPerformed(evt);
            }
        });
        jToolBar1.add(btnZoom);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/java/lab2_thuchanh/icon_cau3/Add.png"))); // NOI18N
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdd);

        btnClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/java/lab2_thuchanh/icon_cau3/Notes.png"))); // NOI18N
        btnClick.setFocusable(false);
        btnClick.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClick.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClick);

        btnChart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/java/lab2_thuchanh/icon_cau3/Bar chart.png"))); // NOI18N
        btnChart.setFocusable(false);
        btnChart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChartActionPerformed(evt);
            }
        });
        jToolBar1.add(btnChart);

        btnLock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/java/lab2_thuchanh/icon_cau3/Lock.png"))); // NOI18N
        btnLock.setFocusable(false);
        btnLock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLockActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLock);

        btnPencil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/java/lab2_thuchanh/icon_cau3/Edit.png"))); // NOI18N
        btnPencil.setFocusable(false);
        btnPencil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPencil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPencil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPencilActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPencil);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("BASIC");

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Open file");
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this, "Save file");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAsActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Save as file");
    }//GEN-LAST:event_btnSaveAsActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Print file");
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(this, "Do you want to exit?", "Exit Form", JOptionPane.YES_NO_OPTION);
        if(opt == JOptionPane.YES_OPTION){
            System .exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmailActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Send file");
    }//GEN-LAST:event_btnEmailActionPerformed

    private void btnCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCallActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Call someone");
    }//GEN-LAST:event_btnCallActionPerformed

    private void btnPresentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresentActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Present file");
    }//GEN-LAST:event_btnPresentActionPerformed

    private void btnAlarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlarmActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Set up time");
    }//GEN-LAST:event_btnAlarmActionPerformed

    private void btnZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoomActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Zoom file");
    }//GEN-LAST:event_btnZoomActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Add new file");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Use cursor");
    }//GEN-LAST:event_btnClickActionPerformed

    private void btnChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChartActionPerformed
        // TODO add your handling code here:Add chart");
        JOptionPane.showMessageDialog(this, "Use chart");
    }//GEN-LAST:event_btnChartActionPerformed

    private void btnLockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLockActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Lock or Unlock");
    }//GEN-LAST:event_btnLockActionPerformed

    private void btnPencilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPencilActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Use pencil");
    }//GEN-LAST:event_btnPencilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cau_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cau_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cau_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cau_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cau_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAlarm;
    private javax.swing.JButton btnCall;
    private javax.swing.JButton btnChart;
    private javax.swing.JButton btnClick;
    private javax.swing.JButton btnEmail;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLock;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnPencil;
    private javax.swing.JButton btnPresent;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveAs;
    private javax.swing.JButton btnZoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
