/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_thuchanh;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.time.temporal.Temporal;
import static java.time.temporal.TemporalQueries.localDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oracle.security.o5logon.d;

/**
 *
 * @author phuon
 */
public class cau2_y2 extends javax.swing.JFrame {

    /**
     * Creates new form cau2_y2
     */
    public cau2_y2() {
        initComponents();
        showComboData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaBenhNhan = new javax.swing.JTextField();
        txtYeuCauKham = new javax.swing.JTextField();
        txtTenBenhNhan = new javax.swing.JTextField();
        dcNgayKham = new com.toedter.calendar.JDateChooser();
        cbBacSi = new javax.swing.JComboBox<>();
        btnDatLichKham = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ma benh nhan");

        jLabel2.setText("Ten benh nhan");

        jLabel3.setText("Ngay kham");

        jLabel4.setText("Yeu cau kham");

        jLabel5.setText("Bac si kham");

        txtMaBenhNhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaBenhNhanKeyPressed(evt);
            }
        });

        txtTenBenhNhan.setEditable(false);

        btnDatLichKham.setText("Dat lich kham");
        btnDatLichKham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLichKhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtYeuCauKham, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtMaBenhNhan)
                            .addComponent(txtTenBenhNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(dcNgayKham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbBacSi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDatLichKham)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(dcNgayKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtYeuCauKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbBacSi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDatLichKham)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String getMaKB() {
        Connection conn = ConnectionOracle.getConn();
        int count = 1;
        String sql = "select * from khambenh";
        try {
            PreparedStatement statement = conn.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                count += 1;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return String.valueOf(count);
    }

    public String getMaBS() {
        Connection conn = ConnectionOracle.getConn();
        String sql = "select mabs from bacsi where tenbs = ?";
        try {
            PreparedStatement statement = conn.prepareStatement(sql);
            String item = (String) cbBacSi.getSelectedItem();
            statement.setString(1, item);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                return rs.getString("mabs");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return null;
    }
    private void btnDatLichKhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLichKhamActionPerformed
        // TODO add your handling code here:
        Connection conn = ConnectionOracle.getConn();//dd-ora-yy
        java.util.Date d = null;
        try {
            d = new SimpleDateFormat("yyyy-MM-dd").parse(LocalDate.now().toString());
        } catch (ParseException ex) {
            Logger.getLogger(cau2_y2.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.util.Date datetime = dcNgayKham.getDate();
        //System.out.println(d.before(datetime));
        if (datetime.before(d)) {
            JOptionPane.showMessageDialog(this, "Ngay kham benh phai lon hon hoac bang ngay hien tai");
        } else {
            String sql = "insert into KHAMBENH (makb, mabn, mabs, ngaykham, yeucaukham) values(?, ?, ?, ?, ?)";
            try {
                PreparedStatement statement = conn.prepareStatement(sql);
                statement.setString(1, getMaKB());
                statement.setString(2, txtMaBenhNhan.getText());
                statement.setString(3, getMaBS());
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MMM/yy");
                String date = sdf.format(dcNgayKham.getDate());
                //System.out.println(date);
                statement.setString(4, date);
                statement.setString(5, txtYeuCauKham.getText());
                int rs = statement.executeUpdate();
                if (rs == 0) {
                    JOptionPane.showMessageDialog(this, "Dat lich khong thanh cong");
                    reset();
                } else {
                    JOptionPane.showMessageDialog(this, "Dat lich thanh cong");
                    reset();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_btnDatLichKhamActionPerformed

    private void txtMaBenhNhanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaBenhNhanKeyPressed
        Connection conn = ConnectionOracle.getConn();//dd-ora-yy
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String sql = "select tenbn from benhnhan where mabn = ?";
            int count = 0;
            try {
                PreparedStatement statement = conn.prepareStatement(sql);
                statement.setString(1, txtMaBenhNhan.getText());
                ResultSet rs = statement.executeQuery();
                while (rs.next()) {
                    txtTenBenhNhan.setText(rs.getString("tenbn"));
                    count += 1;
                }
                if (count == 0) {
                    JOptionPane.showMessageDialog(this, "Benh nhan chua dang ky");
                    reset();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }

    }//GEN-LAST:event_txtMaBenhNhanKeyPressed
    public void reset() {
        txtMaBenhNhan.setText("");
        txtTenBenhNhan.setText("");
        txtYeuCauKham.setText("");
        //dcNgayKham.setDate(LocalDate.now());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cau2_y2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cau2_y2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cau2_y2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cau2_y2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cau2_y2 bai2_y2 = new cau2_y2();
                bai2_y2.setTitle("Dat lich kham");
                bai2_y2.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatLichKham;
    private javax.swing.JComboBox<String> cbBacSi;
    private com.toedter.calendar.JDateChooser dcNgayKham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtMaBenhNhan;
    private javax.swing.JTextField txtTenBenhNhan;
    private javax.swing.JTextField txtYeuCauKham;
    // End of variables declaration//GEN-END:variables

    private void showComboData() {
        ArrayList<String> data = new ArrayList();
        Connection conn = ConnectionOracle.getConn();//dd-ora-yy
        String sql = "Select tenbs from bacsi";
        try {
            PreparedStatement statement = conn.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                data.add(rs.getString("tenbs"));
                //System.out.println(rs.getString("tenbs"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        for (String string : data) {
            cbBacSi.addItem(string);
        }
    }

    private String Date(LocalDate now) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
