/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_thuchanh;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleType;

/**
 *
 * @author phuon
 */
public class cau2_y3 extends javax.swing.JFrame {

    /**
     * Creates new form cau2_y3
     */
    private DefaultTableModel tbModel1, tbModel2;

    public cau2_y3() {
        initComponents();
        showDataBS();
        initTbaleDV();
        showDSDichVu();
        showDSDVBacSiChon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtYeuCauKham = new javax.swing.JTextField();
        txtKetLuan = new javax.swing.JTextField();
        jNgayKham = new com.toedter.calendar.JDateChooser();
        cbBacSi = new javax.swing.JComboBox<>();
        cbBenhNhan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTenDichVu = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbDVBSChon = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ket luan");

        jLabel2.setText("Bac si kham");

        jLabel3.setText("Ten benh nhan");

        jLabel4.setText("Ngay kham");

        jLabel5.setText("Yeu cau kham");

        txtYeuCauKham.setEditable(false);

        jNgayKham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNgayKhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jNgayKhamMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jNgayKhamMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jNgayKhamMouseReleased(evt);
            }
        });
        jNgayKham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNgayKhamKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNgayKhamKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNgayKhamKeyTyped(evt);
            }
        });

        cbBenhNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbBenhNhanMouseClicked(evt);
            }
        });
        cbBenhNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBenhNhanActionPerformed(evt);
            }
        });

        jLabel6.setText("Danh sach dich vu");

        jLabel7.setText("Danh sach dich vu bac si chon");

        tbTenDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Ten dich vu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbTenDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTenDichVuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbTenDichVu);

        tbDVBSChon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ten dich vu", "So luong"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbDVBSChon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDVBSChonMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbDVBSChon);

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tim kiem benh nhan");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtKetLuan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTimKiem))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbBacSi, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtYeuCauKham)
                                .addComponent(jNgayKham, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(btnThem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(cbBacSi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jNgayKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtYeuCauKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKetLuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnThem)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getMaKB() {
        Connection conn = ConnectionOracle.getConn();//dd-ora-yy
        String sql = "Select makb from khambenh where mabs = ? and mabn  = ? and ngaykham = ? and ketluan = ? and yeucaukham = ?";
        try {
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1, getMaBS());
            statement.setString(2, getMaBN());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MMM/yy");
            String date = sdf.format(jNgayKham.getDate());
            //System.out.println(date);
            statement.setString(3, date);
            statement.setString(4, txtKetLuan.getText());
            statement.setString(5, txtYeuCauKham.getText());
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                return rs.getString("makb");
                //System.out.println(rs.getString("tenbs"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return null;
    }


    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        Connection conn = ConnectionOracle.getConn();//dd-ora-yy
        int sluong = tbDVBSChon.getRowCount();
        int sum = 0;
        String madv = null;
        int gia = 0;
        int sldv;
        // them vao thu phi
        for (int i = 0; i < sluong; i++) {
            String sql1 = "select madv, dongia from dichvu where tendv = ?";
            try {
                PreparedStatement statement1 = conn.prepareStatement(sql1);
                statement1.setString(1, (String) tbDVBSChon.getValueAt(i, 0));
                ResultSet rs1 = statement1.executeQuery();
                while (rs1.next()) {
                    madv = rs1.getString("madv");
                    gia = rs1.getInt("dongia");
                }
                if (!madv.isEmpty() && getMaKB() != null) {
                    String sql = "insert into thuphi (makb, madv, soluong, thanhtien) values(?, ?, ?, ?)";
                    PreparedStatement statement = conn.prepareStatement(sql);
                    statement.setString(1, getMaKB());
                    statement.setString(2, madv);
                    sldv = Integer.parseInt((String) tbDVBSChon.getValueAt(i, 1));
                    statement.setInt(3, sldv);
                    statement.setInt(4, gia * sldv);
                    sum += gia * sldv;
                    int check = statement.executeUpdate();
                    if (check > 0) {
                        JOptionPane.showMessageDialog(this, "Them thu phi thanh cong");
                    } else {
                        JOptionPane.showMessageDialog(this, "them thu phi that bai");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "them thu phi that bai");
                }

            } catch (SQLException ex) {
                Logger.getLogger(cau2_y3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // cap nhat kham benh
        if (sum > 0 && getMaKB() != null) {
            String sql2 = "update khambenh set ketluan = ? and thanhtoan = 0 where makb = ?";
            try {
                PreparedStatement statement2 = conn.prepareStatement(sql2);
                statement2.setString(1, txtKetLuan.getText());
                statement2.setString(2, getMaKB());
                int check = statement2.executeUpdate();
                if (check > 0) {
                    JOptionPane.showMessageDialog(this, "Cap nhat kham benh thanh cong");
                } else {
                    JOptionPane.showMessageDialog(this, "Cap nhat kham benh that bai");
                }
            } catch (SQLException ex) {
                Logger.getLogger(cau2_y3.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Cap nhat kham benh that bai");
        }


    }//GEN-LAST:event_btnThemActionPerformed

    private void jNgayKhamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNgayKhamKeyPressed

    }//GEN-LAST:event_jNgayKhamKeyPressed

    private void jNgayKhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNgayKhamMouseClicked

    }//GEN-LAST:event_jNgayKhamMouseClicked

    private void cbBenhNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBenhNhanActionPerformed

    }//GEN-LAST:event_cbBenhNhanActionPerformed

    private void jNgayKhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNgayKhamMousePressed

    }//GEN-LAST:event_jNgayKhamMousePressed

    private void jNgayKhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNgayKhamMouseEntered

    }//GEN-LAST:event_jNgayKhamMouseEntered

    private void jNgayKhamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNgayKhamKeyReleased

    }//GEN-LAST:event_jNgayKhamKeyReleased

    private void jNgayKhamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNgayKhamMouseReleased

    }//GEN-LAST:event_jNgayKhamMouseReleased

    private void jNgayKhamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNgayKhamKeyTyped

    }//GEN-LAST:event_jNgayKhamKeyTyped
    public String getMaBN() {
        Connection conn = ConnectionOracle.getConn();
        String sql = "select mabn from benhnhan where tenbn = ?";
        try {
            PreparedStatement statement = conn.prepareStatement(sql);
            String item = (String) cbBenhNhan.getSelectedItem();
            statement.setString(1, item);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                return rs.getString("mabn");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return null;
    }
    private void cbBenhNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbBenhNhanMouseClicked
        // TODO add your handling code here:
        Connection conn = ConnectionOracle.getConn();//dd-ora-yy
        //System.out.println(date);
        String sql = "select yeucaukham from benhnhan bn join "
                + "                 (select mabn, tenbs, yeucaukham "
                + "                 from khambenh kb join bacsi bs on kb.mabs = bs.mabs "
                + "                 where tenbs = ? and ngaykham = ? and thanhtoan is null) a "
                + "                 on bn.mabn = a.mabn"
                + "                 where tenbn = ?";
        try {
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1, getTenBS());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MMM/yy");
            String date = sdf.format(jNgayKham.getDate());
            //System.out.println(date);
            statement.setString(2, date);
            String item = (String) cbBenhNhan.getSelectedItem();
            statement.setString(3, item);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                txtYeuCauKham.setText(rs.getString("yeucaukham"));
                //System.out.println(rs.getString("tenbs"));
            }
            // System.out.println();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_cbBenhNhanMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        ArrayList<String> data_1 = new ArrayList();
        Connection conn = ConnectionOracle.getConn();//dd-ora-yy
        //System.out.println(date);
        String sql = "select tenbn from benhnhan bn join "
                + "                 (select mabn, tenbs, ngaykham "
                + "                 from khambenh kb join bacsi bs on kb.mabs = bs.mabs "
                + "                 where tenbs = ? and ngaykham = ? and thanhtoan is null) a "
                + "                 on bn.mabn = a.mabn";
        try {
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1, getTenBS());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MMM/yy");
            String date = sdf.format(jNgayKham.getDate());
            //System.out.println(date);
            statement.setString(2, date);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                data_1.add(rs.getString("tenbn"));
                //System.out.println(rs.getString("tenbs"));
            }
            for (String string : data_1) {
                cbBenhNhan.addItem(string);
                System.out.println(string);
            }
            // System.out.println();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tbTenDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTenDichVuMouseClicked
        // TODO add your handling code here:
        int[] index = tbTenDichVu.getSelectedRows();
        Object[] row = new Object[2];
        tbModel2 = (DefaultTableModel) tbDVBSChon.getModel();
        for (int i = 0; i < index.length; i++) {
            String m = JOptionPane.showInputDialog(this, "Nhap so luong dich vu");
            //System.out.println(m);
            row[0] = tbModel1.getValueAt(i, 0);
            row[1] = m;
            tbModel2.addRow(row);
            tbModel1.removeRow(i);
        }

    }//GEN-LAST:event_tbTenDichVuMouseClicked

    private void tbDVBSChonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDVBSChonMouseClicked
        /*   // TODO add your handling code here:
        int[] index = tbDVBSChon.getSelectedRows();
        Object[] row = new Object[1];
        for(int  i = 0; i < index.length; i++){
            row[0] = tbModel2.getValueAt(i, 0);
            tbModel1.addRow(row);
            tbModel2.removeRow(i);
        }
         */
    }//GEN-LAST:event_tbDVBSChonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cau2_y3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cau2_y3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cau2_y3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cau2_y3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cau2_y3 bai2_y3 = new cau2_y3();
                bai2_y3.setTitle("Chi tiet kham benh");
                bai2_y3.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbBacSi;
    private javax.swing.JComboBox<String> cbBenhNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private com.toedter.calendar.JDateChooser jNgayKham;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tbDVBSChon;
    private javax.swing.JTable tbTenDichVu;
    private javax.swing.JTextField txtKetLuan;
    private javax.swing.JTextField txtYeuCauKham;
    // End of variables declaration//GEN-END:variables

    /*private void showDataBN() {
        ArrayList<String> data_1 = new ArrayList();
        Connection conn = ConnectionOracle.getConn();//dd-ora-yy
        String sql = "select tenbn from benhnhan bn join "
                + "                 (select mabn, tenbs, ngaykham "
                + "                 from khambenh kb join bacsi bs on kb.mabs = bs.mabs "
                + "                 where tenbs = ? and ngaykham = ? and thanhtoan is null) a "
                + "                 on bn.mabn = a.mabn";
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yy");
        String date = sdf.format(jNgayKham.getDate());
        try {
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1, getTenBS());
            statement.setString(2, getNgayKham());
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                data_1.add(rs.getString("tenbn"));
                //System.out.println(rs.getString("tenbs"));
            }
            for (String string : data_1) {
                cbBenhNhan.addItem(string);
                System.out.println(string);
            }
            // System.out.println();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }
     */
 /*
    private void showDataBN() {
        ArrayList<String> data_1 = new ArrayList();
        Connection conn = ConnectionOracle.getConn();//dd-ora-yy
        //System.out.println(date);
        String sql = "select tenbn from benhnhan bn join "
                + "                 (select mabn, tenbs, ngaykham "
                + "                 from khambenh kb join bacsi bs on kb.mabs = bs.mabs "
                + "                 where tenbs = ? and ngaykham = ? and thanhtoan is null) a "
                + "                 on bn.mabn = a.mabn";
        try {
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1, getTenBS());
            statement.setString(2, getNgayKham());
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                data_1.add(rs.getString("tenbn"));
                //System.out.println(rs.getString("tenbs"));
            }
            for (String string : data_1) {
                cbBenhNhan.addItem(string);
                System.out.println(string);
            }
            // System.out.println();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }
     */
    private void showDataBS() {
        ArrayList<String> data = new ArrayList();
        Connection conn = ConnectionOracle.getConn();//dd-ora-yy
        String sql = "Select tenbs from bacsi";
        try {
            PreparedStatement statement = conn.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                data.add(rs.getString("tenbs"));
                //System.out.println(rs.getString("tenbs"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        for (String string : data) {
            cbBacSi.addItem(string);
        }
    }

    public String getTenBS() {
        return (String) cbBacSi.getSelectedItem();
    }

    public String getMaBS() {
        Connection conn = ConnectionOracle.getConn();
        String sql = "select mabs from bacsi where tenbs = ?";
        try {
            PreparedStatement statement = conn.prepareStatement(sql);
            String item = (String) cbBacSi.getSelectedItem();
            statement.setString(1, item);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                return rs.getString("mabs");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return null;
    }

    private void initTbaleDV() {
        tbModel1 = new DefaultTableModel();
        tbModel1.setColumnIdentifiers(new String[]{"Ten dich vu"});
    }

    private void showDSDichVu() {
        Connection conn = ConnectionOracle.getConn();
        String sql = "SELECT TENDV FROM DICHVU";
        //tbModel1.setRowCount(0);
        try {
            PreparedStatement statement = conn.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();

            while (rs.next()) {
                tbModel1.addRow(new String[]{rs.getString("TENDV")});
            }

            tbTenDichVu.setModel(tbModel1);
            tbTenDichVu.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(cau2_y3.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void showDSDVBacSiChon() {
        tbModel2 = new DefaultTableModel();
        tbModel2.setColumnIdentifiers(new String[]{"Ten dich vu", "So luong"});
        tbDVBSChon.setModel(tbModel2);
        tbDVBSChon.setVisible(true);
    }

}
